# Generated by Django 3.2.6 on 2022-04-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_recommendations', '0002_auto_20220419_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='description',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Описание'),
        ),
    ]
