# Generated by Django 3.2.6 on 2022-04-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_recommendations', '0003_recommendation_description'),
        ('accounts', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disease',
            field=models.ManyToManyField(blank=True, related_name='users', to='disease_recommendations.Disease'),
        ),
    ]
