# Generated by Django 3.2.6 on 2022-04-15 15:00

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.IntegerField(default=products.models.Product.get_uuid, unique=True, verbose_name='uuid'),
        ),
    ]
