# Generated by Django 3.2.6 on 2022-05-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='photo_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фотографию'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='photo_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фотографию'),
        ),
    ]
